<?php
session_start();if(!isset($_SESSION['username'],$_SESSION['role'])||$_SESSION['role']!=='instructor'){header('Location: /authenication/login/login.php');exit();}
require_once(__DIR__.'/../../Database/db/db.php');require_once(__DIR__.'/../../includes/csrf/csrf.php');$pdo=get_db();$token=instructor_csrf_token();$instructorId=(int)($_SESSION['user_id']??0);$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!instructor_csrf_valid($_POST['csrf_token']??''))$error='Your session expired. Refresh and try again.';
 else{$courseId=(int)($_POST['course_id']??0);$title=trim($_POST['title']??'');$description=trim($_POST['description']??'');$dueDate=trim($_POST['due_date']??'');$owns=$pdo->prepare('SELECT id FROM courses WHERE id=? AND instructor_id=?');$owns->execute([$courseId,$instructorId]);if(!$owns->fetch())$error='Choose one of your courses.';elseif($title==='')$error='Assignment title is required.';elseif($dueDate!==''&&strtotime($dueDate)===false)$error='Enter a valid due date.';else{$insert=$pdo->prepare('INSERT INTO assignments(course_id,title,description,due_date) VALUES(?,?,?,?)');$insert->execute([$courseId,$title,$description,$dueDate?:null]);$notice='Assignment created successfully.';}}
}
$q=$pdo->prepare('SELECT id,title FROM courses WHERE instructor_id=? ORDER BY title');$q->execute([$instructorId]);$courses=$q->fetchAll();
$q=$pdo->prepare('SELECT a.title,a.due_date,c.title AS course_title,COUNT(s.id) AS submissions FROM assignments a JOIN courses c ON c.id=a.course_id LEFT JOIN assignment_submissions s ON s.assignment_id=a.id WHERE c.instructor_id=? GROUP BY a.id ORDER BY a.created_at DESC LIMIT 8');$q->execute([$instructorId]);$assignments=$q->fetchAll();
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">ASSESSMENT CENTER</span><h1>Create assignment</h1><p>Set a task for students enrolled in one of your courses.</p></div><a class="btn btn-outline-secondary" href="/instructor-dashboard/Assignments/view_submissions/view_submissions.php">View submissions</a></div>
<?php if($notice):?><div class="alert alert-success"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="row g-4"><div class="col-xl-5"><section class="card border-0"><div class="card-body p-4"><h2 class="h5 mb-3">Assignment details</h2><?php if(!$courses):?><div class="empty-state"><i class="fa-solid fa-book-open"></i><strong>Create a course first</strong><a href="/instructor-dashboard/Courses/create_course/create_course.php">Create a course</a></div><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><div class="mb-3"><label class="form-label" for="assignmentCourse">Course</label><select class="form-select" id="assignmentCourse" name="course_id" required><option value="">Select a course</option><?php foreach($courses as $c):?><option value="<?=(int)$c['id']?>"><?=htmlspecialchars($c['title'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label" for="assignmentTitle">Title</label><input class="form-control" id="assignmentTitle" name="title" maxlength="100" required></div><div class="mb-3"><label class="form-label" for="assignmentDue">Due date</label><input class="form-control" id="assignmentDue" type="date" name="due_date" min="<?=date('Y-m-d')?>"></div><div class="mb-4"><label class="form-label" for="assignmentDescription">Instructions</label><textarea class="form-control" id="assignmentDescription" name="description" rows="5" placeholder="Explain the task and submission expectations"></textarea></div><button class="btn btn-primary" type="submit"><i class="fa-solid fa-paper-plane me-1"></i>Publish assignment</button></form><?php endif;?></div></section></div><div class="col-xl-7"><section class="card border-0"><div class="table-toolbar"><div><h2 class="h5 mb-1">Recent assignments</h2><small class="text-muted">Assignments across your courses</small></div><a href="/instructor-dashboard/Assignments/grade_assignments/grade_assignments.php">Grade work</a></div><div class="table-responsive"><table class="table instructor-table mb-0"><thead><tr><th>Assignment</th><th>Course</th><th>Due date</th><th>Submissions</th></tr></thead><tbody><?php if(!$assignments):?><tr><td colspan="4" class="text-center text-muted py-4">No assignments yet.</td></tr><?php endif;?><?php foreach($assignments as $a):?><tr><td><strong><?=htmlspecialchars($a['title'],ENT_QUOTES,'UTF-8')?></strong></td><td><?=htmlspecialchars($a['course_title'],ENT_QUOTES,'UTF-8')?></td><td><?=$a['due_date']?htmlspecialchars(date('M j, Y',strtotime($a['due_date'])),ENT_QUOTES,'UTF-8'):'No due date'?></td><td><?=number_format((int)$a['submissions'])?></td></tr><?php endforeach;?></tbody></table></div></section></div></div></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>
