<?php
session_start();if(!isset($_SESSION['username'],$_SESSION['role'])||$_SESSION['role']!=='admin'){header('Location: /authenication/login/login.php');exit();}
require_once(__DIR__.'/../../../Database/db/db.php');$pdo=get_db();$instructors=$pdo->query("SELECT id,username,full_name,email,status,created_at FROM users WHERE role='instructor' ORDER BY created_at DESC")->fetchAll();
$pageTitle = 'Instructor directory';
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">TEACHING TEAM</span><h1>Instructors</h1><p>Review instructor accounts and access status.</p></div><a class="btn btn-primary" href="/Admin-dashboard/Instructors/add_instructor/add_instructor.php"><i class="fa-solid fa-plus me-1"></i>Add instructor</a></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="metric-card"><span class="metric-icon purple"><i class="fa-solid fa-chalkboard-user"></i></span><span class="metric-label">Instructors</span><strong><?=number_format(count($instructors))?></strong><small>Teaching team</small></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon green"><i class="fa-solid fa-user-check"></i></span><span class="metric-label">Active</span><strong><?=number_format(count(array_filter($instructors,fn($i)=>$i['status']==='active')))?></strong><small>Enabled accounts</small></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon blue"><i class="fa-solid fa-calendar-plus"></i></span><span class="metric-label">Recently added</span><strong><?=number_format(count(array_filter($instructors,fn($i)=>strtotime($i['created_at'])>=strtotime('-30 days'))))?></strong><small>Past 30 days</small></div></div></div>
<section class="card border-0"><div class="table-toolbar"><div><h2 class="h5 mb-1">Instructor directory</h2><div class="text-muted small">Search and sort instructor records.</div></div><div class="table-search"><i class="fa-solid fa-magnifying-glass"></i><input type="search" data-table-search="instructorsTable" placeholder="Search instructors" aria-label="Search instructors"></div></div><div class="table-responsive"><table class="table admin-table mb-0" id="instructorsTable" data-admin-sort><thead><tr><th data-sort>Instructor</th><th data-sort>Email</th><th data-sort>Status</th><th data-sort>Joined</th><th class="text-end">Manage</th></tr></thead><tbody>
<?php if(!$instructors):?><tr><td colspan="5"><div class="empty-state"><i class="fa-regular fa-folder-open"></i><strong>No instructors found</strong></div></td></tr><?php endif;?>
<?php foreach($instructors as $i):$name=$i['full_name']?:$i['username'];?><tr><td><div class="table-person"><span class="person-avatar instructor-avatar"><?=strtoupper(substr($name,0,1))?></span><span><strong><?=htmlspecialchars($name,ENT_QUOTES,'UTF-8')?></strong><small>@<?=htmlspecialchars($i['username'],ENT_QUOTES,'UTF-8')?></small></span></div></td><td><?=htmlspecialchars($i['email'],ENT_QUOTES,'UTF-8')?></td><td><span class="status-pill <?=$i['status']==='active'?'status-active':'status-inactive'?>"><i></i><?=htmlspecialchars(ucfirst($i['status']),ENT_QUOTES,'UTF-8')?></span></td><td><?=htmlspecialchars(date('M j, Y',strtotime($i['created_at'])),ENT_QUOTES,'UTF-8')?></td><td class="text-end"><a class="table-icon-action" href="/Admin-dashboard/user_management/user_management.php?role=instructor&amp;search=<?=rawurlencode($i['username'])?>" title="Manage account"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></td></tr><?php endforeach;?>
</tbody></table></div></section></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>
