<?php
session_start();if(!isset($_SESSION['username'],$_SESSION['role'])||$_SESSION['role']!=='instructor'){header('Location: /authenication/login/login.php');exit();}
require_once(__DIR__.'/../../includes/db/db.php');require_once(__DIR__.'/../../includes/csrf/csrf.php');$pdo=get_db();$token=instructor_csrf_token();$instructorId=(int)($_SESSION['user_id']??0);$notice='';$error='';$studentsQuery=$pdo->prepare("SELECT DISTINCT u.id,u.username,u.full_name FROM enrollments e JOIN courses c ON c.id=e.course_id JOIN users u ON u.id=e.user_id WHERE c.instructor_id=? AND u.role='student' ORDER BY COALESCE(u.full_name,u.username)");$studentsQuery->execute([$instructorId]);$students=$studentsQuery->fetchAll();$studentIds=array_map('intval',array_column($students,'id'));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!instructor_csrf_valid($_POST['csrf_token']??''))$error='Your session expired. Refresh and try again.';
 else{$recipient=(int)($_POST['recipient_id']??0);$content=trim($_POST['content']??'');if(!in_array($recipient,$studentIds,true))$error='Select a student enrolled in one of your courses.';elseif($content==='')$error='Write a message first.';else{$q=$pdo->prepare('INSERT INTO messages(sender_id,receiver_id,content) VALUES(?,?,?)');$q->execute([$instructorId,$recipient,$content]);$notice='Your message was sent.';}}
}
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">STUDENT CONNECTIONS</span><h1>Start a discussion</h1><p>Send a private message to a learner enrolled in your course.</p></div></div><?php if($notice):?><div class="alert alert-success"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?><section class="card border-0" style="max-width:760px"><div class="card-body p-4"><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><div class="mb-3"><label class="form-label" for="recipient">Student</label><select class="form-select" id="recipient" name="recipient_id" required><option value="">Choose a student</option><?php foreach($students as $student):?><option value="<?=(int)$student['id']?>"><?=htmlspecialchars($student['full_name']?:$student['username'],ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars($student['username'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select><?php if(!$students):?><div class="form-text">Enrolled students will appear after they join one of your courses.</div><?php endif;?></div><div class="mb-4"><label class="form-label" for="messageContent">Message</label><textarea class="form-control" id="messageContent" name="content" rows="6" maxlength="5000" required></textarea></div><div class="d-flex justify-content-between"><a class="btn btn-light" href="/instructor-dashboard/Students/messages/messages.php">Back to messages</a><button class="btn btn-primary" type="submit" <?=$students?'':'disabled'?>>Send message</button></div></form></div></section></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>
