<?php
session_start();
if (!isset($_SESSION['username'], $_SESSION['role']) || $_SESSION['role'] !== 'admin') { header('Location: /authenication/login/login.php'); exit(); }
require_once(__DIR__ . '/../../Database/db/db.php'); require_once(__DIR__ . '/../includes/csrf/csrf.php');
$pdo = get_db(); $token = generate_csrf_token(); $notice = ''; $error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if (!validate_csrf_token($_POST['csrf_token'] ?? '')) { $error = 'Your session token expired. Refresh and try again.'; }
  elseif (($_POST['action'] ?? '') === 'add_user') {
    $fullName=trim($_POST['full_name']??''); $username=trim($_POST['username']??''); $email=trim($_POST['email']??''); $role=$_POST['role']??'student'; $password=$_POST['password']??'';
    if ($username==='' || !filter_var($email,FILTER_VALIDATE_EMAIL) || strlen($password)<8 || !in_array($role,['admin','instructor','student'],true)) { $error='Enter a valid username and email, choose a role, and use a password with at least 8 characters.'; }
    else { try { $q=$pdo->prepare('INSERT INTO users (username,email,password,full_name,role,status) VALUES (?,?,?,?,?,?)'); $q->execute([$username,$email,password_hash($password,PASSWORD_DEFAULT),$fullName,$role,'active']); $notice='User account created.'; } catch(PDOException $e) { $error='Could not add the account. That username or email may already be in use.'; } }
  } elseif (($_POST['action'] ?? '') === 'update_user') {
    $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT); $fullName=trim($_POST['full_name']??''); $username=trim($_POST['username']??''); $email=trim($_POST['email']??''); $role=$_POST['role']??''; $status=$_POST['status']??'';
    if (!$id || $username==='' || !filter_var($email,FILTER_VALIDATE_EMAIL) || !in_array($role,['admin','instructor','student'],true) || !in_array($status,['active','inactive'],true)) { $error='Check the account details and try again.'; }
    else { try { $q=$pdo->prepare('UPDATE users SET full_name=?,username=?,email=?,role=?,status=? WHERE id=?'); $q->execute([$fullName,$username,$email,$role,$status,$id]); $notice='User details updated.'; } catch(PDOException $e) { $error='Could not update this account. Confirm the email and username are unique.'; } }
  } elseif (($_POST['action'] ?? '') === 'delete_user') {
    $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT);
    if (!$id) { $error='The selected account was not found.'; }
    elseif ((int)($_SESSION['user_id']??0)===$id) { $error='You cannot delete the account you are currently using.'; }
    else { try { $q=$pdo->prepare('SELECT role,username FROM users WHERE id=?'); $q->execute([$id]); $target=$q->fetch(); if (!$target) { $error='The account no longer exists.'; } elseif ($target['username'] === ($_SESSION['username'] ?? '')) { $error='You cannot delete the account you are currently using.'; } elseif ($target['role']==='admin' && (int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn()<=1) { $error='The last administrator account cannot be deleted.'; } else { $q=$pdo->prepare('DELETE FROM users WHERE id=?'); $q->execute([$id]); $notice='User account deleted.'; } } catch(PDOException $e) { $error='This account is linked to other records and cannot be deleted. Set its status to inactive instead.'; } }
  }
}
$roleFilter=$_GET['role']??''; $search=trim($_GET['search']??''); $filters=[]; $params=[];
if (in_array($roleFilter,['admin','instructor','student'],true)) { $filters[]='role=?'; $params[]=$roleFilter; }
if ($search!=='') { $filters[]='(full_name LIKE ? OR username LIKE ? OR email LIKE ? OR CAST(id AS CHAR) LIKE ?)'; array_push($params,"%$search%","%$search%","%$search%","%$search%"); }
$whereSql = $filters ? ' WHERE ' . implode(' AND ', $filters) : '';
$countQuery = $pdo->prepare('SELECT COUNT(*) FROM users' . $whereSql);
$countQuery->execute($params);
$totalUsers = (int)$countQuery->fetchColumn();
$pageSize = 25;
$totalPages = max(1, (int)ceil($totalUsers / $pageSize));
$currentPage = min($totalPages, max(1, (int)($_GET['page'] ?? 1)));
$offset = ($currentPage - 1) * $pageSize;
$sql = 'SELECT id,full_name,username,email,role,status,created_at FROM users' . $whereSql . ' ORDER BY created_at DESC LIMIT ? OFFSET ?';
$q = $pdo->prepare($sql);
foreach ($params as $index => $param) $q->bindValue($index + 1, $param, PDO::PARAM_STR);
$q->bindValue(count($params) + 1, $pageSize, PDO::PARAM_INT);
$q->bindValue(count($params) + 2, $offset, PDO::PARAM_INT);
$q->execute();
$users = $q->fetchAll(PDO::FETCH_ASSOC);
$pageTitle = 'User management';
include(__DIR__.'/../includes/header/header.php'); include(__DIR__.'/../includes/navbar/navbar.php'); include(__DIR__.'/../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">PEOPLE & ACCESS</span><h1>User management</h1><p>Manage account details, roles, and access status.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addUserModal"><i class="fa-solid fa-user-plus me-1"></i>Add user</button></div>
<?php if($notice):?><div class="alert alert-success alert-dismissible fade show"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?><?php if($error):?><div class="alert alert-danger alert-dismissible fade show"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><div class="metric-card"><span class="metric-icon purple"><i class="fa-solid fa-users"></i></span><span class="metric-label">Accounts</span><strong><?=number_format(count($users))?></strong><small>In this view</small></div></div><div class="col-sm-6 col-xl-3"><div class="metric-card"><span class="metric-icon green"><i class="fa-solid fa-user-check"></i></span><span class="metric-label">Active</span><strong><?=number_format(count(array_filter($users,fn($u)=>$u['status']==='active')))?></strong><small>Enabled accounts</small></div></div><div class="col-sm-6 col-xl-3"><div class="metric-card"><span class="metric-icon blue"><i class="fa-solid fa-chalkboard-user"></i></span><span class="metric-label">Instructors</span><strong><?=number_format(count(array_filter($users,fn($u)=>$u['role']==='instructor')))?></strong><small>In this view</small></div></div><div class="col-sm-6 col-xl-3"><div class="metric-card"><span class="metric-icon amber"><i class="fa-solid fa-user-graduate"></i></span><span class="metric-label">Students</span><strong><?=number_format(count(array_filter($users,fn($u)=>$u['role']==='student')))?></strong><small>In this view</small></div></div></div>
<section class="card border-0"><div class="table-toolbar"><div><h2 class="h5 mb-1">Accounts</h2><div class="text-muted small"><?=number_format($totalUsers)?> accounts found</div></div><form method="get" class="d-flex gap-2 flex-wrap"><select name="role" class="form-select form-select-sm" aria-label="Filter role"><option value="">All roles</option><?php foreach(['admin'=>'Admin','instructor'=>'Instructor','student'=>'Student'] as $key=>$label):?><option value="<?=$key?>" <?=$roleFilter===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select><input class="form-control form-control-sm" name="search" value="<?=htmlspecialchars($search,ENT_QUOTES,'UTF-8')?>" placeholder="Search name or email"><button class="btn btn-sm btn-outline-primary">Filter</button></form></div><div class="table-responsive"><table class="table admin-table mb-0" data-admin-sort><thead><tr><th data-sort>User</th><th data-sort>Role</th><th data-sort>Status</th><th data-sort>Joined</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php if(!$users):?><tr><td colspan="5"><div class="empty-state"><i class="fa-regular fa-folder-open"></i><strong>No accounts found</strong><span>Try another search or role filter.</span></div></td></tr><?php endif;?>
<?php foreach($users as $u):$name=$u['full_name']?:$u['username'];?><tr><td><div class="table-person"><span class="person-avatar"><?=strtoupper(substr($name,0,1))?></span><span><strong><?=htmlspecialchars($name,ENT_QUOTES,'UTF-8')?></strong><small><?=htmlspecialchars($u['email'],ENT_QUOTES,'UTF-8')?></small></span></div></td><td><span class="role-pill"><?=htmlspecialchars(ucfirst($u['role']),ENT_QUOTES,'UTF-8')?></span></td><td><span class="status-pill <?=$u['status']==='active'?'status-active':'status-inactive'?>"><i></i><?=htmlspecialchars(ucfirst($u['status']),ENT_QUOTES,'UTF-8')?></span></td><td><?=htmlspecialchars(date('M j, Y',strtotime($u['created_at'])),ENT_QUOTES,'UTF-8')?></td><td><div class="table-actions"><button class="table-icon-action" type="button" title="Edit" data-bs-toggle="modal" data-bs-target="#editUserModal" data-edit-user data-id="<?=(int)$u['id']?>" data-full-name="<?=htmlspecialchars($name,ENT_QUOTES,'UTF-8')?>" data-username="<?=htmlspecialchars($u['username'],ENT_QUOTES,'UTF-8')?>" data-email="<?=htmlspecialchars($u['email'],ENT_QUOTES,'UTF-8')?>" data-role="<?=$u['role']?>" data-status="<?=$u['status']?>"><i class="fa-solid fa-pen"></i></button><form method="post" data-confirm-message="Delete <?=htmlspecialchars($name,ENT_QUOTES,'UTF-8')?>? This cannot be undone."><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="id" value="<?=(int)$u['id']?>"><button class="table-icon-action danger" title="Delete" type="submit"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr><?php endforeach;?>
</tbody></table></div><?php if($totalPages > 1): ?><nav class="admin-pagination" aria-label="Account pages"><span>Page <?=number_format($currentPage)?> of <?=number_format($totalPages)?></span><div><?php $prevQuery=$_GET; $prevQuery['page']=max(1,$currentPage-1); $nextQuery=$_GET; $nextQuery['page']=min($totalPages,$currentPage+1); ?><a class="btn btn-sm btn-outline-secondary <?=$currentPage<=1?'disabled':''?>" href="?<?=htmlspecialchars(http_build_query($prevQuery),ENT_QUOTES,'UTF-8')?>" <?=$currentPage<=1?'aria-disabled="true" tabindex="-1"':''?>>Previous</a><a class="btn btn-sm btn-outline-secondary <?=$currentPage>=$totalPages?'disabled':''?>" href="?<?=htmlspecialchars(http_build_query($nextQuery),ENT_QUOTES,'UTF-8')?>" <?=$currentPage>=$totalPages?'aria-disabled="true" tabindex="-1"':''?>>Next</a></div></nav><?php endif; ?></section></div></main>
<div class="modal fade" id="addUserModal" tabindex="-1" aria-labelledby="addUserTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow"><form method="post"><div class="modal-header"><h2 class="modal-title h5" id="addUserTitle">Add account</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="add_user"><label class="form-label">Full name</label><input class="form-control mb-3" name="full_name"><label class="form-label">Username</label><input class="form-control mb-3" name="username" required><label class="form-label">Email</label><input class="form-control mb-3" name="email" type="email" required><label class="form-label">Role</label><select class="form-select mb-3" name="role"><option value="student">Student</option><option value="instructor">Instructor</option><option value="admin">Administrator</option></select><label class="form-label">Temporary password</label><input class="form-control" type="password" name="password" minlength="8" autocomplete="new-password" required></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Create account</button></div></form></div></div></div>
<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow"><form id="editUserForm" method="post"><div class="modal-header"><h2 class="modal-title h5" id="editUserTitle">Edit account</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="update_user"><input type="hidden" name="id"><label class="form-label">Full name</label><input class="form-control mb-3" name="full_name" required><label class="form-label">Username</label><input class="form-control mb-3" name="username" required><label class="form-label">Email</label><input class="form-control mb-3" name="email" type="email" required><div class="row g-3"><div class="col"><label class="form-label">Role</label><select class="form-select" name="role"><option value="student">Student</option><option value="instructor">Instructor</option><option value="admin">Admin</option></select></div><div class="col"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save changes</button></div></form></div></div></div>
<?php include(__DIR__.'/../includes/footer/footer.php');?>


