<?php
session_start();if(!isset($_SESSION['username'],$_SESSION['role'])||$_SESSION['role']!=='instructor'){header('Location: /authenication/login/login.php');exit();}
require_once(__DIR__.'/../../Database/db/db.php');require_once(__DIR__.'/../../includes/csrf/csrf.php');$pdo=get_db();$instructorId=(int)($_SESSION['user_id']??0);$token=instructor_csrf_token();$notice='';$error='';
$q=$pdo->prepare("SELECT DISTINCT u.id,u.username,u.full_name,u.email FROM enrollments e JOIN courses c ON c.id=e.course_id JOIN users u ON u.id=e.user_id WHERE c.instructor_id=? AND u.role='student' ORDER BY COALESCE(u.full_name,u.username)");$q->execute([$instructorId]);$students=$q->fetchAll();$studentIds=array_map('intval',array_column($students,'id'));
$selectedId=(int)($_GET['student_id']??$_POST['recipient_id']??0);if(!in_array($selectedId,$studentIds,true))$selectedId=$studentIds[0]??0;
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['send_message'])){
 if(!instructor_csrf_valid($_POST['csrf_token']??''))$error='Your session expired. Refresh the page and try again.';
 else{$recipient=(int)($_POST['recipient_id']??0);$content=trim($_POST['content']??'');if(!in_array($recipient,$studentIds,true))$error='Select a student enrolled in one of your courses.';elseif($content==='')$error='Write a message before sending.';else{$q=$pdo->prepare('INSERT INTO messages(sender_id,receiver_id,content) VALUES(?,?,?)');$q->execute([$instructorId,$recipient,$content]);$selectedId=$recipient;$notice='Message sent.';}}
}
$thread=[];if($selectedId){$q=$pdo->prepare('SELECT m.id,m.sender_id,m.receiver_id,m.content,m.sent_at,u.username AS sender_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE (m.sender_id=? AND m.receiver_id=?) OR (m.sender_id=? AND m.receiver_id=?) ORDER BY m.sent_at ASC');$q->execute([$instructorId,$selectedId,$selectedId,$instructorId]);$thread=$q->fetchAll();}
$selectedName='';foreach($students as $student){if((int)$student['id']===$selectedId){$selectedName=$student['full_name']?:$student['username'];break;}}
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">STUDENT CONNECTIONS</span><h1>Messages</h1><p>Continue conversations with learners in your courses.</p></div></div><?php if($notice):?><div class="alert alert-success"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-4"><section class="card border-0 h-100"><div class="table-toolbar"><div><h2 class="h6 mb-0">My students</h2><small class="text-muted"><?=count($students)?> learners</small></div></div><div class="list-group list-group-flush"><?php if(!$students):?><div class="p-4 text-muted small">Students will appear here when they enroll in your courses.</div><?php endif;?><?php foreach($students as $student):$studentName=$student['full_name']?:$student['username'];?><a href="?student_id=<?=(int)$student['id']?>" class="list-group-item list-group-item-action d-flex align-items-center gap-2 <?=((int)$student['id']===$selectedId)?'active':''?>"><span class="person-avatar"><?=strtoupper(substr($studentName,0,1))?></span><span><strong><?=htmlspecialchars($studentName,ENT_QUOTES,'UTF-8')?></strong><small class="d-block"><?=htmlspecialchars($student['email'],ENT_QUOTES,'UTF-8')?></small></span></a><?php endforeach;?></div></section></div>
<div class="col-lg-8"><section class="card border-0 h-100"><div class="table-toolbar border-bottom"><div><h2 class="h6 mb-0"><?=htmlspecialchars($selectedName?:'Conversation',ENT_QUOTES,'UTF-8')?></h2><small class="text-muted">Private instructor conversation</small></div></div><div class="card-body"><div class="chat-history mb-3" aria-live="polite"><?php if(!$thread):?><div class="empty-state"><i class="fa-regular fa-comments"></i><strong>No messages yet</strong><span>Send a note to start the conversation.</span></div><?php else:foreach($thread as $row):$mine=(int)$row['sender_id']===$instructorId;?><div class="chat-message <?=$mine?'mine':''?>"><small><?=htmlspecialchars($mine?'You':$row['sender_name'],ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars(date('M j, g:i A',strtotime($row['sent_at'])),ENT_QUOTES,'UTF-8')?></small><div><?=nl2br(htmlspecialchars($row['content'],ENT_QUOTES,'UTF-8'))?></div></div><?php endforeach;endif;?></div><?php if($selectedId):?><form method="post" class="border-top pt-3"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="recipient_id" value="<?=$selectedId?>"><textarea class="form-control mb-2" name="content" rows="3" placeholder="Write a message" maxlength="5000" required></textarea><div class="d-flex justify-content-end"><button class="btn btn-primary" name="send_message" value="1"><i class="fa-solid fa-paper-plane me-1"></i>Send message</button></div></form><?php endif;?></div></section></div></div></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>
