document.addEventListener('DOMContentLoaded',function(){
 const side=document.getElementById('adminSidebar'),toggle=document.getElementById('toggleSidebar'),backdrop=document.getElementById('sidebarBackdrop'),mobile=()=>matchMedia('(max-width: 991.98px)').matches;
 function showSide(open){if(!side||!toggle||!backdrop)return;side.classList.toggle('is-open',open);backdrop.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');document.body.classList.toggle('sidebar-open',open&&mobile());}
 toggle?.addEventListener('click',()=>showSide(!side.classList.contains('is-open')));backdrop?.addEventListener('click',()=>showSide(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')showSide(false);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.topbar-search input')?.focus();}});window.addEventListener('resize',()=>{if(!mobile())showSide(false)});side?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(mobile())showSide(false)}));
 document.querySelectorAll('[data-sidebar-group-toggle]').forEach(b=>b.addEventListener('click',()=>{const p=document.getElementById(b.getAttribute('aria-controls'));if(!p)return;const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));p.hidden=open;}));
 document.querySelectorAll('[data-table-search]').forEach(i=>{const t=document.getElementById(i.dataset.tableSearch);if(t)i.addEventListener('input',()=>{const q=i.value.trim().toLowerCase();t.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q));});});
 document.querySelectorAll('table[data-admin-sort]').forEach(t=>t.querySelectorAll('thead th[data-sort]').forEach((h,n)=>{h.tabIndex=0;h.setAttribute('role','button');const sort=()=>{const b=t.tBodies[0];if(!b)return;const d=h.dataset.direction==='asc'?'desc':'asc';t.querySelectorAll('[data-sort]').forEach(x=>delete x.dataset.direction);h.dataset.direction=d;Array.from(b.rows).sort((x,y)=>{const a=x.cells[n]?.textContent.trim()||'',c=y.cells[n]?.textContent.trim()||'',num=!isNaN(Number(a))&&!isNaN(Number(c)),v=num?Number(a)-Number(c):a.localeCompare(c,undefined,{numeric:true,sensitivity:'base'});return d==='asc'?v:-v;}).forEach(r=>b.appendChild(r));};h.addEventListener('click',sort);h.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();sort();}});}));
 let pending=null;const el=document.getElementById('adminConfirmModal'),modal=el&&window.bootstrap?bootstrap.Modal.getOrCreateInstance(el):null;
 document.querySelectorAll('form[data-confirm-message]').forEach(f=>f.addEventListener('submit',e=>{if(f.dataset.confirmed==='true'){f.dataset.confirmed='false';return;}e.preventDefault();pending=f;const m=document.getElementById('adminConfirmMessage');if(m)m.textContent=f.dataset.confirmMessage;if(modal)modal.show();else if(confirm(f.dataset.confirmMessage))f.submit();}));
 document.getElementById('adminConfirmProceed')?.addEventListener('click',()=>{if(!pending)return;pending.dataset.confirmed='true';modal?.hide();pending.requestSubmit();pending=null;});
 document.querySelectorAll('[data-edit-user]').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('editUserForm');if(!f)return;const map={id:'id',full_name:'fullName',username:'username',email:'email',role:'role',status:'status'};Object.keys(map).forEach(k=>{if(f.elements[k])f.elements[k].value=b.dataset[map[k]]||'';});}));
 document.querySelectorAll('[data-edit-course]').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('editCourseForm');if(!f)return;['id','title','category','description'].forEach(k=>{if(f.elements[k])f.elements[k].value=b.dataset[k]||'';});}));
 document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach(e=>{if(window.bootstrap)new bootstrap.Tooltip(e);});
});


