<?php
session_start();if(!isset($_SESSION['username'],$_SESSION['role'])||$_SESSION['role']!=='instructor'){header('Location: /authenication/login/login.php');exit();}
require_once(__DIR__.'/../../includes/db/db.php');require_once(__DIR__.'/../../includes/csrf/csrf.php');$pdo=get_db();$token=instructor_csrf_token();$instructorId=(int)($_SESSION['user_id']??0);$notice='';$error='';
$q=$pdo->prepare('SELECT id,title FROM courses WHERE instructor_id=? ORDER BY title');$q->execute([$instructorId]);$courses=$q->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!instructor_csrf_valid($_POST['csrf_token']??''))$error='Your session expired. Refresh and try again.';
 else{$courseId=(int)($_POST['course_id']??0);$title=trim($_POST['title']??'');$content=trim($_POST['content']??'');$priority=$_POST['priority']??'medium';$owns=$pdo->prepare('SELECT id FROM courses WHERE id=? AND instructor_id=?');$owns->execute([$courseId,$instructorId]);if(!$owns->fetch())$error='Select one of your courses.';elseif($title===''||$content==='')$error='Enter a title and announcement.';elseif(!in_array($priority,['low','medium','high'],true))$error='Choose a valid priority.';else{$q=$pdo->prepare('INSERT INTO announcements(title,content,course_id,priority,created_by) VALUES(?,?,?,?,?)');$q->execute([$title,$content,$courseId,$priority,$instructorId]);$notice='Announcement posted to your course.';}}
}
$q=$pdo->prepare('SELECT a.id,a.title,a.content,a.priority,a.created_at,c.title AS course_title,u.username AS author FROM announcements a LEFT JOIN courses c ON c.id=a.course_id LEFT JOIN users u ON u.id=a.created_by WHERE a.course_id IS NULL OR c.instructor_id=? ORDER BY a.created_at DESC LIMIT 30');$q->execute([$instructorId]);$announcements=$q->fetchAll();
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">COURSE COMMUNITY</span><h1>Announcements</h1><p>Share course updates and review academy-wide notices.</p></div></div><?php if($notice):?><div class="alert alert-success"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="row g-4"><div class="col-xl-5"><section class="card border-0"><div class="card-body p-4"><h2 class="h5">Post a course update</h2><?php if(!$courses):?><p class="text-muted small">Create a course before posting an announcement.</p><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><div class="mb-3"><label class="form-label" for="announcementCourse">Course</label><select class="form-select" id="announcementCourse" name="course_id" required><option value="">Select a course</option><?php foreach($courses as $course):?><option value="<?=(int)$course['id']?>"><?=htmlspecialchars($course['title'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label" for="announcementTitle">Title</label><input class="form-control" id="announcementTitle" name="title" maxlength="255" required></div><div class="mb-3"><label class="form-label" for="announcementPriority">Priority</label><select class="form-select" id="announcementPriority" name="priority"><option value="low">Routine</option><option value="medium" selected>Important</option><option value="high">Urgent</option></select></div><div class="mb-3"><label class="form-label" for="announcementContent">Message</label><textarea class="form-control" id="announcementContent" name="content" rows="5" required></textarea></div><button class="btn btn-primary">Post announcement</button></form><?php endif;?></div></section></div><div class="col-xl-7"><div class="d-flex flex-column gap-3"><?php if(!$announcements):?><section class="card border-0"><div class="empty-state"><i class="fa-regular fa-bell-slash"></i><strong>No announcements yet</strong></div></section><?php endif;?><?php foreach($announcements as $item):?><article class="card border-0"><div class="card-body p-4"><div class="d-flex justify-content-between gap-3"><div><span class="badge text-bg-light mb-2"><?=htmlspecialchars($item['course_title']??'Academy-wide',ENT_QUOTES,'UTF-8')?></span><h2 class="h5 mb-1"><?=htmlspecialchars($item['title'],ENT_QUOTES,'UTF-8')?></h2></div><span class="status-pill <?=$item['priority']==='high'?'status-waiting':'status-good'?>"><i></i><?=htmlspecialchars(ucfirst($item['priority']),ENT_QUOTES,'UTF-8')?></span></div><p class="text-muted mt-3 mb-3"><?=nl2br(htmlspecialchars($item['content'],ENT_QUOTES,'UTF-8'))?></p><small class="text-muted">By <?=htmlspecialchars($item['author']??'Academy team',ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars(date('M j, Y',strtotime($item['created_at'])),ENT_QUOTES,'UTF-8')?></small></div></article><?php endforeach;?></div></div></div></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>
