<?php
session_start();if(!isset($_SESSION['username'],$_SESSION['role'])||$_SESSION['role']!=='instructor'){header('Location: /authenication/login/login.php');exit();}
require_once(__DIR__.'/../../Database/db/db.php');require_once(__DIR__.'/../../includes/csrf/csrf.php');$pdo=get_db();$token=instructor_csrf_token();$message='';$error='';$id=(int)($_SESSION['user_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!instructor_csrf_valid($_POST['csrf_token']??''))$error='Your session expired. Refresh and try again.';
 else{$title=trim($_POST['title']??'');$description=trim($_POST['description']??'');$category=trim($_POST['category']??'');if($title==='')$error='A course title is required.';elseif(mb_strlen($title)>100)$error='Course titles must be 100 characters or fewer.';else{$q=$pdo->prepare("INSERT INTO courses(title,description,category,instructor_id,status) VALUES(?,?,?,?, 'draft')");$q->execute([$title,$description,$category,$id]);$message='Course created as a draft. You can review it in My courses.';}}
}
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">COURSE BUILDER</span><h1>Create a course</h1><p>Start with the course details. New courses are saved as drafts.</p></div><a class="btn btn-outline-secondary" href="/instructor-dashboard/Courses/all_courses/all_courses.php">My courses</a></div>
<?php if($message):?><div class="alert alert-success alert-dismissible fade show"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?><?php if($error):?><div class="alert alert-danger alert-dismissible fade show"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?>
<div class="row g-4"><div class="col-xl-8"><section class="card border-0"><div class="card-body p-4"><h2 class="h5 mb-1">Course information</h2><p class="text-muted small mb-4">Add a clear title and a short description to help students understand the course.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><div class="mb-3"><label for="courseTitle" class="form-label">Course title</label><input id="courseTitle" class="form-control" name="title" maxlength="100" placeholder="e.g. Introduction to Web Development" required></div><div class="mb-3"><label for="courseCategory" class="form-label">Category</label><input id="courseCategory" class="form-control" name="category" maxlength="50" placeholder="e.g. Technology"></div><div class="mb-4"><label for="courseDescription" class="form-label">Description</label><textarea id="courseDescription" class="form-control" name="description" rows="6" placeholder="What will students learn?"></textarea></div><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk me-1"></i>Save draft</button></form></div></section></div><div class="col-xl-4"><section class="card border-0"><div class="card-body p-4"><span class="metric-icon violet position-static mb-3"><i class="fa-solid fa-lightbulb"></i></span><h2 class="h5">A useful course starts with</h2><ul class="text-muted small ps-3 mb-0"><li class="mb-2">A specific, student-friendly title</li><li class="mb-2">A short summary of the learning goals</li><li>One clear subject category</li></ul></div></section></div></div></div></main>
<?php include(__DIR__.'/../../includes/footer/footer.php');?>
