<?php
session_start();
if (!isset($_SESSION['username'], $_SESSION['role']) || $_SESSION['role'] !== 'admin') { header('Location: /authenication/login/login.php'); exit(); }
require_once(__DIR__ . '/../../../Database/db/db.php'); require_once(__DIR__ . '/../../includes/csrf/csrf.php');
$pdo=get_db(); $token=generate_csrf_token(); $notice=''; $error='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
 if (!validate_csrf_token($_POST['csrf_token']??'')) $error='Your session token expired. Refresh the page and try again.';
 elseif (($_POST['action']??'')==='update_course') {
  $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT); $title=trim($_POST['title']??''); $category=trim($_POST['category']??''); $description=trim($_POST['description']??'');
  if (!$id||$title==='') $error='A course title is required.'; else { $q=$pdo->prepare('UPDATE courses SET title=?,category=?,description=? WHERE id=?'); $q->execute([$title,$category,$description,$id]); $notice='Course details updated.'; }
 } elseif (($_POST['action']??'')==='delete_course') {
  $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT);
  if (!$id) $error='The selected course was not found.'; else { try { $q=$pdo->prepare('DELETE FROM courses WHERE id=?'); $q->execute([$id]); $notice='Course deleted.'; } catch(PDOException $e) { $error='This course is linked to other records and cannot be deleted. You can unpublish it from course settings instead.'; } }
 }
}
$search=trim($_GET['search']??''); $where=''; $params=[]; if($search!==''){$where='WHERE c.title LIKE ? OR u.full_name LIKE ? OR c.category LIKE ?';$params=array_fill(0,3,"%$search%");}
$count=$pdo->prepare("SELECT COUNT(*) FROM courses c LEFT JOIN users u ON u.id=c.instructor_id $where");$count->execute($params);$total=(int)$count->fetchColumn();
$q=$pdo->prepare("SELECT c.id,c.title,c.category,c.description,c.created_at,COALESCE(u.full_name,u.username,'Unassigned') AS instructor_name,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id) AS enrolled_count FROM courses c LEFT JOIN users u ON u.id=c.instructor_id $where ORDER BY c.created_at DESC");$q->execute($params);$courses=$q->fetchAll();
$pageTitle = 'Course directory';
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">LEARNING CATALOG</span><h1>Courses</h1><p>Review course content, instructors, and enrollment activity.</p></div><a class="btn btn-primary" href="/Admin-dashboard/Courses/add_course/add_course.php"><i class="fa-solid fa-plus me-1"></i>Add course</a></div>
<?php if($notice):?><div class="alert alert-success alert-dismissible fade show"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?><?php if($error):?><div class="alert alert-danger alert-dismissible fade show"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="metric-card"><span class="metric-icon purple"><i class="fa-solid fa-book-open"></i></span><span class="metric-label">Courses</span><strong><?=number_format($total)?></strong><small>In the learning catalog</small></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon blue"><i class="fa-solid fa-user-group"></i></span><span class="metric-label">Enrollments</span><strong><?=number_format(array_sum(array_column($courses,'enrolled_count')))?></strong><small>For courses in this view</small></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon green"><i class="fa-solid fa-layer-group"></i></span><span class="metric-label">Categories</span><strong><?=count(array_unique(array_filter(array_column($courses,'category'))))?></strong><small>Represented in results</small></div></div></div>
<section class="card border-0"><div class="table-toolbar"><div><h2 class="h5 mb-1">Course catalog</h2><div class="text-muted small"><?=$total?> courses found</div></div><form method="get" class="d-flex gap-2"><input class="form-control form-control-sm" name="search" value="<?=htmlspecialchars($search,ENT_QUOTES,'UTF-8')?>" placeholder="Search courses"><button class="btn btn-sm btn-outline-primary">Search</button><a class="btn btn-sm btn-light" href="?">Reset</a></form></div><div class="table-responsive"><table class="table admin-table mb-0" data-admin-sort><thead><tr><th data-sort>Course</th><th data-sort>Category</th><th data-sort>Instructor</th><th data-sort>Students</th><th data-sort>Created</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php if(!$courses):?><tr><td colspan="6"><div class="empty-state"><i class="fa-regular fa-folder-open"></i><strong>No courses found</strong><span>Try a different search.</span></div></td></tr><?php endif;?>
<?php foreach($courses as $c):?><tr><td><div class="table-person"><span class="course-avatar"><i class="fa-solid fa-book"></i></span><span><strong><?=htmlspecialchars($c['title'],ENT_QUOTES,'UTF-8')?></strong><small>Course #<?=(int)$c['id']?></small></span></div></td><td><span class="role-pill"><?=htmlspecialchars($c['category']?:'Uncategorized',ENT_QUOTES,'UTF-8')?></span></td><td><?=htmlspecialchars($c['instructor_name'],ENT_QUOTES,'UTF-8')?></td><td><strong><?=number_format((int)$c['enrolled_count'])?></strong></td><td><?=htmlspecialchars(date('M j, Y',strtotime($c['created_at'])),ENT_QUOTES,'UTF-8')?></td><td><div class="table-actions"><button class="table-icon-action" type="button" title="Edit course" data-bs-toggle="modal" data-bs-target="#editCourseModal" data-edit-course data-id="<?=(int)$c['id']?>" data-title="<?=htmlspecialchars($c['title'],ENT_QUOTES,'UTF-8')?>" data-category="<?=htmlspecialchars($c['category']??'',ENT_QUOTES,'UTF-8')?>" data-description="<?=htmlspecialchars($c['description']??'',ENT_QUOTES,'UTF-8')?>"><i class="fa-solid fa-pen"></i></button><form method="post" data-confirm-message="Delete <?=htmlspecialchars($c['title'],ENT_QUOTES,'UTF-8')?>? This cannot be undone."><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="delete_course"><input type="hidden" name="id" value="<?=(int)$c['id']?>"><button class="table-icon-action danger" type="submit" title="Delete course"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr><?php endforeach;?>
</tbody></table></div></section></div></main>
<div class="modal fade" id="editCourseModal" tabindex="-1" aria-labelledby="editCourseTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow"><form id="editCourseForm" method="post"><div class="modal-header"><h2 class="modal-title h5" id="editCourseTitle">Edit course</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="update_course"><input type="hidden" name="id"><label class="form-label">Title</label><input class="form-control mb-3" name="title" maxlength="100" required><label class="form-label">Category</label><input class="form-control mb-3" name="category" maxlength="50"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="4"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save changes</button></div></form></div></div></div>
<?php include(__DIR__.'/../../includes/footer/footer.php'); ?>
