<?php
session_start(); if (!isset($_SESSION['username'],$_SESSION['role']) || $_SESSION['role']!=='admin') { header('Location: /authenication/login/login.php'); exit(); }
require_once(__DIR__.'/../../../Database/db/db.php'); $pdo=get_db();
$q=$pdo->prepare('SELECT u.id,u.username,u.email,u.full_name,u.status,COUNT(e.id) AS course_count,MAX(e.created_at) AS last_enrolled FROM users u LEFT JOIN enrollments e ON e.user_id=u.id WHERE u.role=? GROUP BY u.id ORDER BY u.created_at DESC'); $q->execute(['student']); $students=$q->fetchAll();
$pageTitle = 'Student directory';
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">LEARNER DIRECTORY</span><h1>Students</h1><p>Review learner accounts and their enrollment activity.</p></div><a class="btn btn-primary" href="/Admin-dashboard/Students/enroll_student/enroll_student.php"><i class="fa-solid fa-user-plus me-1"></i>Enroll student</a></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="metric-card"><span class="metric-icon purple"><i class="fa-solid fa-user-graduate"></i></span><span class="metric-label">Students</span><strong><?=number_format(count($students))?></strong><small>Registered learners</small></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon green"><i class="fa-solid fa-user-check"></i></span><span class="metric-label">Active accounts</span><strong><?=number_format(count(array_filter($students,fn($s)=>$s['status']==='active')))?></strong><small>Enabled accounts</small></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon blue"><i class="fa-solid fa-book-open"></i></span><span class="metric-label">Enrollments</span><strong><?=number_format(array_sum(array_column($students,'course_count')))?></strong><small>Across all students</small></div></div></div>
<section class="card border-0"><div class="table-toolbar"><div><h2 class="h5 mb-1">Student directory</h2><div class="text-muted small">Search and sort student records.</div></div><div class="table-search"><i class="fa-solid fa-magnifying-glass"></i><input type="search" data-table-search="studentsTable" placeholder="Search students" aria-label="Search students"></div></div><div class="table-responsive"><table id="studentsTable" class="table admin-table mb-0" data-admin-sort><thead><tr><th data-sort>Student</th><th data-sort>Email</th><th data-sort>Enrollments</th><th data-sort>Last enrolled</th><th data-sort>Status</th><th class="text-end">Manage</th></tr></thead><tbody>
<?php if(!$students):?><tr><td colspan="6"><div class="empty-state"><i class="fa-regular fa-folder-open"></i><strong>No students found</strong></div></td></tr><?php endif;?>
<?php foreach($students as $s):$name=$s['full_name']?:$s['username'];?><tr><td><div class="table-person"><span class="person-avatar"><?=strtoupper(substr($name,0,1))?></span><span><strong><?=htmlspecialchars($name,ENT_QUOTES,'UTF-8')?></strong><small>@<?=htmlspecialchars($s['username'],ENT_QUOTES,'UTF-8')?></small></span></div></td><td><?=htmlspecialchars($s['email'],ENT_QUOTES,'UTF-8')?></td><td><span class="role-pill"><?=(int)$s['course_count']?> courses</span></td><td><?=$s['last_enrolled']?htmlspecialchars(date('M j, Y',strtotime($s['last_enrolled'])),ENT_QUOTES,'UTF-8'):'—'?></td><td><span class="status-pill <?=$s['status']==='active'?'status-active':'status-inactive'?>"><i></i><?=htmlspecialchars(ucfirst($s['status']),ENT_QUOTES,'UTF-8')?></span></td><td class="text-end"><a class="table-icon-action" href="/Admin-dashboard/user_management/user_management.php?role=student&amp;search=<?=rawurlencode($s['username'])?>" title="Manage account"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></td></tr><?php endforeach;?>
</tbody></table></div></section></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>
