<?php
session_start();if(($_SESSION['role']??'')!=='admin'){header('Location: /authenication/login/login.php');exit;}
require_once(__DIR__.'/../../../Database/db/db.php');require_once(__DIR__.'/../../includes/csrf/csrf.php');$pdo=get_db();$id=(int)($_SESSION['user_id']??0);$message='';$type='info';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!validate_csrf_token($_POST['csrf_token']??'')){$message='Session expired. Refresh and try again.';$type='danger';}else{$current=$_POST['current_password']??'';$next=$_POST['new_password']??'';$confirm=$_POST['confirm_password']??'';$q=$pdo->prepare('SELECT password FROM users WHERE id=?');$q->execute([$id]);$row=$q->fetch(PDO::FETCH_ASSOC);if(strlen($next)<8||$next!==$confirm){$message='Use at least 8 characters and make sure both new passwords match.';$type='warning';}elseif(!$row||!password_verify($current,$row['password'])){$message='Current password is incorrect.';$type='danger';}else{$q=$pdo->prepare('UPDATE users SET password=? WHERE id=?');$q->execute([password_hash($next,PASSWORD_DEFAULT),$id]);$message='Password updated successfully.';$type='success';}}}
$pageTitle='Account security';include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">ACCOUNT SECURITY</span><h1>Account</h1><p>Update your administrator password.</p></div></div><?php if($message):?><div class="alert alert-<?=$type?>"><?=htmlspecialchars($message)?></div><?php endif;?><div class="row g-4"><div class="col-xl-7"><section class="card border-0"><div class="card-body p-4"><form method="post" class="row g-3"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generate_csrf_token(),ENT_QUOTES,'UTF-8')?>"><div class="col-12"><label class="form-label">Current password</label><input class="form-control" name="current_password" type="password" autocomplete="current-password" required></div><div class="col-md-6"><label class="form-label">New password</label><input class="form-control" name="new_password" type="password" minlength="8" autocomplete="new-password" required></div><div class="col-md-6"><label class="form-label">Confirm password</label><input class="form-control" name="confirm_password" type="password" minlength="8" autocomplete="new-password" required></div><div class="col-12"><button class="btn btn-primary">Update password</button></div></form></div></section></div></div></div></main><?php include(__DIR__.'/../../includes/footer/footer.php');?>



