<?php
session_start();
if (!isset($_SESSION['username'],$_SESSION['role']) || $_SESSION['role'] !== 'admin') { header('Location: /authenication/login/login.php'); exit(); }
require_once(__DIR__.'/../../../Database/db/db.php'); require_once(__DIR__.'/../../includes/csrf/csrf.php');
$pdo=get_db(); $token=generate_csrf_token(); $message=''; $messageType='success';
$instructors=$pdo->query("SELECT id,COALESCE(full_name,username) AS display_name FROM users WHERE role='instructor' AND status='active' ORDER BY display_name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['add_course'])) {
 if(!validate_csrf_token($_POST['csrf_token']??'')) {$message='Your session token expired. Refresh the page and try again.';$messageType='danger';}
 else {$title=trim($_POST['course_name']??'');$instructorId=filter_input(INPUT_POST,'instructor_id',FILTER_VALIDATE_INT);$description=trim($_POST['description']??'');$category=trim($_POST['category']??'');
  if($title===''||!$instructorId){$message='Course title and instructor are required.';$messageType='danger';}
  else {$check=$pdo->prepare("SELECT id FROM users WHERE id=? AND role='instructor' AND status='active'");$check->execute([$instructorId]);if(!$check->fetch()){$message='Choose an active instructor from the list.';$messageType='danger';}else{$insert=$pdo->prepare('INSERT INTO courses (title,description,category,instructor_id) VALUES (?,?,?,?)');$insert->execute([$title,$description,$category,$instructorId]);$message='Course created successfully.';}}
 }
}
$q=$pdo->query("SELECT c.id,c.title,c.category,c.created_at,COALESCE(u.full_name,u.username,'Unassigned') AS instructor,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id) AS enrolled_count FROM courses c LEFT JOIN users u ON u.id=c.instructor_id ORDER BY c.created_at DESC LIMIT 8");$recent=$q->fetchAll();
$pageTitle = 'Add a course';
include(__DIR__.'/../../includes/header/header.php');include(__DIR__.'/../../includes/navbar/navbar.php');include(__DIR__.'/../../includes/sidebar/sidebar.php');
?>
<main class="main-content"><div class="container-fluid"><div class="page-heading"><div><span class="page-kicker">LEARNING CATALOG</span><h1>Add a course</h1><p>Create a course and assign it to an active instructor.</p></div><a class="btn btn-outline-secondary" href="/Admin-dashboard/Courses/all_courses/all_courses.php">View all courses</a></div>
<?php if($message):?><div class="alert alert-<?=$messageType?> alert-dismissible fade show"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?>
<div class="row g-4"><div class="col-xl-5"><section class="card border-0"><div class="card-body p-4"><h2 class="h5 mb-1">Course details</h2><p class="text-muted small mb-4">Enter the basic information learners will see.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($token,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="add_course" value="1"><div class="mb-3"><label class="form-label" for="courseName">Course title</label><input class="form-control" id="courseName" name="course_name" maxlength="100" required></div><div class="mb-3"><label class="form-label" for="courseCategory">Category</label><input class="form-control" id="courseCategory" name="category" maxlength="50" placeholder="e.g. Technology"></div><div class="mb-3"><label class="form-label" for="courseInstructor">Instructor</label><select class="form-select" id="courseInstructor" name="instructor_id" required><option value="">Choose an instructor</option><?php foreach($instructors as $i):?><option value="<?=(int)$i['id']?>"><?=htmlspecialchars($i['display_name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select><?php if(!$instructors):?><div class="form-text text-warning">Add an active instructor before creating a course.</div><?php endif;?></div><div class="mb-4"><label class="form-label" for="courseDescription">Description</label><textarea class="form-control" id="courseDescription" name="description" rows="5" placeholder="Describe the course"></textarea></div><div class="d-flex gap-2"><button class="btn btn-primary" type="submit" <?=$instructors?'':'disabled'?>>Create course</button><a class="btn btn-light" href="/Admin-dashboard/Courses/all_courses/all_courses.php">Cancel</a></div></form></div></section></div>
<div class="col-xl-7"><section class="card border-0"><div class="table-toolbar"><div><h2 class="h5 mb-1">Recently added</h2><div class="text-muted small">Latest courses in the catalog</div></div><a class="small text-decoration-none" href="/Admin-dashboard/Courses/all_courses/all_courses.php">See all</a></div><div class="table-responsive"><table class="table admin-table mb-0"><thead><tr><th>Course</th><th>Instructor</th><th>Students</th><th>Created</th></tr></thead><tbody><?php if(!$recent):?><tr><td colspan="4" class="text-center text-muted py-4">No courses yet.</td></tr><?php endif;?><?php foreach($recent as $c):?><tr><td><strong><?=htmlspecialchars($c['title'],ENT_QUOTES,'UTF-8')?></strong><small class="d-block text-muted"><?=htmlspecialchars($c['category']?:'Uncategorized',ENT_QUOTES,'UTF-8')?></small></td><td><?=htmlspecialchars($c['instructor'],ENT_QUOTES,'UTF-8')?></td><td><?=(int)$c['enrolled_count']?></td><td><?=htmlspecialchars(date('M j, Y',strtotime($c['created_at'])),ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;?></tbody></table></div></section></div></div></div></main>
<?php include(__DIR__.'/../../includes/footer/footer.php');?>


