document.addEventListener('DOMContentLoaded',function(){
 const side=document.getElementById('instructorSidebar'),toggle=document.getElementById('toggleSidebar'),backdrop=document.getElementById('sidebarBackdrop'),mobile=()=>matchMedia('(max-width: 991.98px)').matches;
 function setSidebar(open){if(!side||!toggle||!backdrop)return;side.classList.toggle('is-open',open);backdrop.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');document.body.classList.toggle('sidebar-open',open&&mobile());}
 toggle?.addEventListener('click',()=>setSidebar(!side.classList.contains('is-open')));backdrop?.addEventListener('click',()=>setSidebar(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')setSidebar(false);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.topbar-search input')?.focus();}});window.addEventListener('resize',()=>{if(!mobile())setSidebar(false)});side?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(mobile())setSidebar(false)}));
 document.querySelectorAll('[data-nav-toggle]').forEach(button=>button.addEventListener('click',()=>{const panel=document.getElementById(button.getAttribute('aria-controls'));if(!panel)return;const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));panel.hidden=expanded;}));
 const themeButton=document.getElementById('themeToggle');function setTheme(dark){document.documentElement.classList.toggle('dark-theme',dark);localStorage.setItem('instructor-theme',dark?'dark':'light');if(themeButton)themeButton.innerHTML=dark?'<i class="fa-regular fa-sun"></i>':'<i class="fa-regular fa-moon"></i>';}
 setTheme(localStorage.getItem('instructor-theme')==='dark');themeButton?.addEventListener('click',()=>setTheme(!document.documentElement.classList.contains('dark-theme')));
 document.querySelectorAll('[data-table-search]').forEach(input=>{const table=document.getElementById(input.dataset.tableSearch);if(table)input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();table.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q));});});
 document.querySelectorAll('table[data-sortable]').forEach(table=>table.querySelectorAll('thead th[data-sort]').forEach((heading,index)=>{heading.tabIndex=0;heading.setAttribute('role','button');const sort=()=>{const body=table.tBodies[0];if(!body)return;const direction=heading.dataset.direction==='asc'?'desc':'asc';table.querySelectorAll('th[data-sort]').forEach(th=>delete th.dataset.direction);heading.dataset.direction=direction;Array.from(body.rows).sort((a,b)=>{const x=a.cells[index]?.textContent.trim()||'',y=b.cells[index]?.textContent.trim()||'',numeric=x!==''&&y!==''&&!isNaN(Number(x))&&!isNaN(Number(y)),value=numeric?Number(x)-Number(y):x.localeCompare(y,undefined,{numeric:true,sensitivity:'base'});return direction==='asc'?value:-value;}).forEach(row=>body.appendChild(row));};heading.addEventListener('click',sort);heading.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();sort();}});}));
 let pending=null;const confirmElement=document.getElementById('instructorConfirmModal'),confirmModal=confirmElement&&window.bootstrap?bootstrap.Modal.getOrCreateInstance(confirmElement):null;document.querySelectorAll('form[data-confirm-message]').forEach(form=>form.addEventListener('submit',event=>{if(form.dataset.confirmed==='true'){form.dataset.confirmed='false';return;}event.preventDefault();pending=form;const message=document.getElementById('instructorConfirmMessage');if(message)message.textContent=form.dataset.confirmMessage;if(confirmModal)confirmModal.show();else if(confirm(form.dataset.confirmMessage))form.submit();}));document.getElementById('instructorConfirmProceed')?.addEventListener('click',()=>{if(!pending)return;pending.dataset.confirmed='true';confirmModal?.hide();pending.requestSubmit();pending=null;});
 document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach(element=>{if(window.bootstrap)new bootstrap.Tooltip(element);});
});
