<?php
// Example: generate a simple PDF with FPDF and send it via PHPMailer
// Usage: php examples/send_pdf_with_phpmailer.php
// Configure SMTP credentials below before running.

require(__DIR__ . '/../fpdf/fpdf.php');

if (!file_exists(__DIR__ . '/../vendor/autoload.php')) {
    fwrite(STDERR, "Missing vendor/autoload.php. Run composer install in the project root.\n");
    exit(1);
}
require(__DIR__ . '/../vendor/autoload.php');

$mailerClass = 'PHPMailer\\PHPMailer\\PHPMailer';
$exceptionClass = 'PHPMailer\\PHPMailer\\Exception';

if (!class_exists($mailerClass)) {
    fwrite(STDERR, "PHPMailer class not found. Please install: composer require phpmailer/phpmailer\n");
    exit(1);
}

// --- PDF generation ---
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'TECHWORLD ACADEMY - Demo PDF',0,1,'C');
$pdf->Ln(5);
$pdf->SetFont('Arial','',12);
$pdf->MultiCell(0,6,"This is a generated PDF used as an example for attaching to email via PHPMailer.\nGenerated on: " . date('c'));

// Save to a temporary file
$tmpDir = sys_get_temp_dir();
$filename = $tmpDir . DIRECTORY_SEPARATOR . 'techworld_demo_' . time() . '.pdf';
$pdf->Output('F', $filename);

if (!file_exists($filename)) {
    echo "Failed to create PDF at $filename\n";
    exit(1);
}

// --- Email send ---
try {
    $mail = new $mailerClass(true);
} catch (Exception $e) {
    fwrite(STDERR, "Failed to instantiate PHPMailer: " . $e->getMessage() . "\n");
    @unlink($filename);
    exit(1);
}

// Read SMTP configuration from environment variables (recommended)
$smtpHost = getenv('SMTP_HOST') ?: null;
$smtpPort = getenv('SMTP_PORT') ?: null;
$smtpUser = getenv('SMTP_USER') ?: null;
$smtpPass = getenv('SMTP_PASS') ?: null;
$smtpFrom = getenv('SMTP_FROM') ?: null;
$smtpFromName = getenv('SMTP_FROM_NAME') ?: 'TechWorld Demo';
$smtpSecure = getenv('SMTP_SECURE') ?: 'tls'; // 'tls' or 'ssl'

$to = getenv('MAIL_TO') ?: 'recipient@example.com';
$subject = getenv('MAIL_SUBJECT') ?: 'Demo PDF from TechWorld Academy';
$body = getenv('MAIL_BODY') ?: 'Please find the attached demo PDF generated by FPDF.';

// Basic required config check when running from CLI:
if (php_sapi_name() === 'cli') {
    $missing = [];
    foreach (['SMTP_HOST' => $smtpHost, 'SMTP_PORT' => $smtpPort, 'SMTP_USER' => $smtpUser, 'SMTP_PASS' => $smtpPass, 'SMTP_FROM' => $smtpFrom] as $k => $v) {
        if (empty($v)) $missing[] = $k;
    }
    if (!empty($missing)) {
        fwrite(STDERR, "Missing required environment variables: " . implode(', ', $missing) . "\n");
        fwrite(STDERR, "Set them in your shell or run the CLI example after configuring SMTP. See README.md for PowerShell instructions.\n");
        // Cleanup temporary file
        @unlink($filename);
        exit(1);
    }
}

try {
    //Server settings
    $mail->isSMTP();
    $mail->Host       = $smtpHost;
    $mail->SMTPAuth   = true;
    $mail->Username   = $smtpUser;
    $mail->Password   = $smtpPass;
    $mail->Port       = (int)$smtpPort;
    $mail->SMTPSecure = (strtolower($smtpSecure) === 'ssl') ? 'ssl' : 'tls';

    //Recipients
    $from = $smtpFrom;
    $fromName = $smtpFromName;
    $mail->setFrom($from, $fromName);
    $mail->addAddress($to);

    // Attachments
    $mail->addAttachment($filename, 'techworld_demo.pdf');

    // Content
    $mail->isHTML(false);
    $mail->Subject = $subject;
    $mail->Body    = $body;

    $mail->send();
    echo "Message has been sent.\n";
} catch (Exception $e) {
    fwrite(STDERR, "Message could not be sent. PHPMailer Exception: {$mail->ErrorInfo}\n");
    fwrite(STDERR, "Exception message: " . $e->getMessage() . "\n");
}

// Cleanup temporary file
@unlink($filename);

